<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jassToPscript"
    nsURI="http://www.JassToPscript" nsPrefix="jassToPscript">
  <eClassifiers xsi:type="ecore:EClass" name="Prog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elems" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Entity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalBlock" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vars" upperBound="-1" eType="ecore:EClass platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Constant"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mult" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Literal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Expr"/>
  <eClassifiers xsi:type="ecore:EClass" name="NativeDef" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" eType="ecore:EClass platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//FormalParameters"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="ecore:EClass platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//ReturnType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormalParameters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//FormalParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormalParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDef" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntLiteral" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolLiteral" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnsNothing" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//ReturnType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParamNothing" eSuperTypes="platform:/resource/de.peeeq.jassToPscript/src-gen/de/peeeq/JassToPscript.ecore#//FormalParameters"/>
</ecore:EPackage>
