plugins {
    id 'java'
    id 'application'
}

repositories {
    maven { url 'https://jitpack.io' }
    mavenCentral()
}

dependencies {
    implementation 'com.github.inwc3:wc3libs:9a11e1f089'
    implementation 'com.google.guava:guava:31.1-jre'
    testImplementation 'org.testng:testng:7.11.0'
}

application {
    mainClass = 'objEditing.abilities.GenAbilities'
}

run {
    workingDir = project.projectDir
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
            exclude 'test/**'
        }
    }
}

test {
    useTestNG()
}
