//generated by parseq
package de.peeeq.wurstscript.jassAst;

public abstract class JassVars extends ParseqList<JassVar> implements JassAstElement{
	public JassVars copy() {
		JassVars result = new JassVarsImpl();
		for (JassVar elem : this) {
			result.add(elem.copy());
		}
		return result;
	}
	public abstract void accept(JassFunction.Visitor v);
	public abstract void accept(JassVars.Visitor v);
	public abstract void accept(JassProg.Visitor v);
	public abstract void accept(JassFunctions.Visitor v);
	public interface Visitor {
		void visit(JassSimpleVar jassSimpleVar);
		void visit(JassVars jassVars);
		void visit(JassArrayVar jassArrayVar);
	}
	public static abstract class DefaultVisitor implements Visitor {
		@Override public void visit(JassSimpleVar jassSimpleVar) {}
		@Override public void visit(JassVars jassVars) {}
		@Override public void visit(JassArrayVar jassArrayVar) {}
	}
}
