//generated by parseq
package de.peeeq.wurstscript.jassAst;

class JassSimpleVarsImpl extends JassSimpleVars implements JassAstElementIntern {
 	private JassAstElement parent;
	public JassAstElement getParent() { return parent; }
	public void setParent(JassAstElement parent) {
		if (parent != null && this.parent != null) { 			throw new Error("Parent of " + this + " already set: " + this.parent + "\ntried to change to " + parent); 		}
		this.parent = parent;
	}

	protected void other_setParentToThis(JassSimpleVar t) {
		((JassAstElementIntern) t).setParent(this);
	}
	protected void other_clearParent(JassSimpleVar t) {
		((JassAstElementIntern) t).setParent(null);
	}
	@Override public void accept(JassProg.Visitor v) {
		for (JassSimpleVar i : this ) {
			i.accept(v);
		}
		v.visit(this);
	}
	@Override public void accept(JassFunction.Visitor v) {
		for (JassSimpleVar i : this ) {
			i.accept(v);
		}
		v.visit(this);
	}
	@Override public void accept(JassSimpleVars.Visitor v) {
		for (JassSimpleVar i : this ) {
			i.accept(v);
		}
		v.visit(this);
	}
	@Override public void accept(JassFunctions.Visitor v) {
		for (JassSimpleVar i : this ) {
			i.accept(v);
		}
		v.visit(this);
	}
	@Override public String toString() {
		String result =  "JassSimpleVars(";
		boolean first = true;
		for (JassSimpleVar i : this ) {
			if (!first) { result +=", "; }
			if (result.length() > 1000) { result +="..."; break; }
			result += i;
			first = false;
		}
		result +=  ")";
		return result;
	}
}
