/*
* generated by Xtext
*/
package de.peeeq.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.peeeq.services.JassToPscriptGrammarAccess;

public class JassToPscriptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JassToPscriptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.peeeq.parser.antlr.internal.InternalJassToPscriptParser createParser(XtextTokenStream stream) {
		return new de.peeeq.parser.antlr.internal.InternalJassToPscriptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Prog";
	}
	
	public JassToPscriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JassToPscriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
