package de.peeeq.parseq;

public enum TokenType {
	LPAR, RPAR, EQ, COMMA, PIPE, ABSTRACT_SYNTAX, IDENTIFIER, EOF, STRING_LITERAL, ERROR, STAR, PACKAGE, DOT, IMPLEMENTED_BY, ATTRIBUTES, RETURNS, LT, GT
}
