/*
 * WurstEditorView.java
 */

package wursteditor;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rtextarea.RTextScrollPane;
import org.jdesktop.application.Application;

/**
 * The application's main frame.
 */
public class WurstEditorView extends FrameView {

    public WurstEditorView(SingleFrameApplication app) {
        super(app);

        initComponents();
        
        getRSTASplitPane().removeAll();
        
        ResourceMap resourceMap = Application.getInstance(wursteditor.WurstEditorApp.class).getContext().getResourceMap(WurstEditorView.class);
        
        BufferedImage image = null;
        try {
            image = ImageIO.read(
                new File("./src/wursteditor/resources/WEditIcon.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        getFrame().setIconImage(image);
        // status bar initialization - message timeout, idle icon and busy animation, etc
        
    }
    
    

    @Action
    public void showAboutBox() {
        if (getAboutBox() == null) {
            JFrame mainFrame = WurstEditorApp.getApplication().getMainFrame();
            aboutBox = new WurstEditorAboutBox(mainFrame);
            getAboutBox().setLocationRelativeTo(mainFrame);
        }
        WurstEditorApp.getApplication().show(getAboutBox());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        fileManagementToolbar = new javax.swing.JToolBar();
        newFileButton = new javax.swing.JButton();
        newProjectButton = new javax.swing.JButton();
        openProjectButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        saveAllButton = new javax.swing.JButton();
        undoRedoToolbar = new javax.swing.JToolBar();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        checkCompileToolbar = new javax.swing.JToolBar();
        compileButton = new javax.swing.JButton();
        leftRightSplitPane = new javax.swing.JSplitPane();
        tabbedFilePane = new javax.swing.JTabbedPane();
        treePanel = new javax.swing.JPanel();
        treeScrollPane = new javax.swing.JScrollPane();
        fileTree = new javax.swing.JTree();
        syntaxErrorSplitpane = new javax.swing.JSplitPane();
        RSTASplitPane = new javax.swing.JTabbedPane();
        rSyntaxScrollPane = new RTextScrollPane((RSyntaxTextArea)syntaxCodeArea);
        syntaxCodeArea = new RSyntaxTextArea();
        ErrorListScrollPane = new javax.swing.JScrollPane();
        errorList = new javax.swing.JList();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        fileManagementToolbar.setRollover(true);
        fileManagementToolbar.setName("fileManagementToolbar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wursteditor.WurstEditorApp.class).getContext().getResourceMap(WurstEditorView.class);
        newFileButton.setIcon(resourceMap.getIcon("newFileButton.icon")); // NOI18N
        newFileButton.setText(resourceMap.getString("newFileButton.text")); // NOI18N
        newFileButton.setFocusable(false);
        newFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newFileButton.setName("newFileButton"); // NOI18N
        newFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fileManagementToolbar.add(newFileButton);

        newProjectButton.setIcon(resourceMap.getIcon("newProjectButton.icon")); // NOI18N
        newProjectButton.setText(resourceMap.getString("newProjectButton.text")); // NOI18N
        newProjectButton.setFocusable(false);
        newProjectButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newProjectButton.setName("newProjectButton"); // NOI18N
        newProjectButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fileManagementToolbar.add(newProjectButton);

        openProjectButton.setIcon(resourceMap.getIcon("openProjectButton.icon")); // NOI18N
        openProjectButton.setText(resourceMap.getString("openProjectButton.text")); // NOI18N
        openProjectButton.setFocusable(false);
        openProjectButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openProjectButton.setName("openProjectButton"); // NOI18N
        openProjectButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fileManagementToolbar.add(openProjectButton);

        saveFileButton.setIcon(resourceMap.getIcon("saveFileButton.icon")); // NOI18N
        saveFileButton.setText(resourceMap.getString("saveFileButton.text")); // NOI18N
        saveFileButton.setFocusable(false);
        saveFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveFileButton.setName("saveFileButton"); // NOI18N
        saveFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fileManagementToolbar.add(saveFileButton);

        saveAllButton.setIcon(resourceMap.getIcon("saveAllButton.icon")); // NOI18N
        saveAllButton.setText(resourceMap.getString("saveAllButton.text")); // NOI18N
        saveAllButton.setFocusable(false);
        saveAllButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveAllButton.setName("saveAllButton"); // NOI18N
        saveAllButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fileManagementToolbar.add(saveAllButton);

        undoRedoToolbar.setRollover(true);
        undoRedoToolbar.setName("undoRedoToolbar"); // NOI18N

        undoButton.setIcon(resourceMap.getIcon("undoButton.icon")); // NOI18N
        undoButton.setText(resourceMap.getString("undoButton.text")); // NOI18N
        undoButton.setFocusable(false);
        undoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        undoButton.setName("undoButton"); // NOI18N
        undoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        undoRedoToolbar.add(undoButton);

        redoButton.setIcon(resourceMap.getIcon("redoButton.icon")); // NOI18N
        redoButton.setText(resourceMap.getString("redoButton.text")); // NOI18N
        redoButton.setFocusable(false);
        redoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        redoButton.setName("redoButton"); // NOI18N
        redoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        undoRedoToolbar.add(redoButton);

        checkCompileToolbar.setRollover(true);
        checkCompileToolbar.setName("checkCompileToolbar"); // NOI18N

        compileButton.setIcon(resourceMap.getIcon("compileButton.icon")); // NOI18N
        compileButton.setText(resourceMap.getString("compileButton.text")); // NOI18N
        compileButton.setFocusable(false);
        compileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        compileButton.setName("compileButton"); // NOI18N
        compileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        checkCompileToolbar.add(compileButton);

        leftRightSplitPane.setName("leftRightSplitPane"); // NOI18N

        tabbedFilePane.setName("tabbedFilePane"); // NOI18N

        treePanel.setName("treePanel"); // NOI18N

        treeScrollPane.setBorder(null);
        treeScrollPane.setName("treeScrollPane"); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Packages");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Util");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Blub");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Math");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Vector");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        fileTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        fileTree.setName("fileTree"); // NOI18N
        treeScrollPane.setViewportView(fileTree);

        javax.swing.GroupLayout treePanelLayout = new javax.swing.GroupLayout(treePanel);
        treePanel.setLayout(treePanelLayout);
        treePanelLayout.setHorizontalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(treeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        treePanelLayout.setVerticalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(treeScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        tabbedFilePane.addTab(resourceMap.getString("treePanel.TabConstraints.tabTitle"), resourceMap.getIcon("treePanel.TabConstraints.tabIcon"), treePanel); // NOI18N

        leftRightSplitPane.setLeftComponent(tabbedFilePane);

        syntaxErrorSplitpane.setDividerLocation(430);
        syntaxErrorSplitpane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        syntaxErrorSplitpane.setResizeWeight(1.0);
        syntaxErrorSplitpane.setName("syntaxErrorSplitpane"); // NOI18N

        RSTASplitPane.setName("RSTASplitPane"); // NOI18N

        rSyntaxScrollPane.setName("rSyntaxScrollPane"); // NOI18N

        syntaxCodeArea.setColumns(20);
        syntaxCodeArea.setRows(60);
        syntaxCodeArea.setName("syntaxCodeArea"); // NOI18N
        rSyntaxScrollPane.setViewportView(syntaxCodeArea);

        RSTASplitPane.addTab(resourceMap.getString("rSyntaxScrollPane.TabConstraints.tabTitle"), rSyntaxScrollPane); // NOI18N

        syntaxErrorSplitpane.setLeftComponent(RSTASplitPane);
        RSTASplitPane.getAccessibleContext().setAccessibleParent(syntaxErrorSplitpane);

        ErrorListScrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        ErrorListScrollPane.setName("ErrorListScrollPane"); // NOI18N

        errorList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        errorList.setCellRenderer(new ErrorListCellRenderer());
        errorList.setName("errorList"); // NOI18N
        ErrorListScrollPane.setViewportView(errorList);

        syntaxErrorSplitpane.setRightComponent(ErrorListScrollPane);

        leftRightSplitPane.setRightComponent(syntaxErrorSplitpane);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(fileManagementToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undoRedoToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkCompileToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(516, Short.MAX_VALUE))
            .addComponent(leftRightSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fileManagementToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkCompileToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(undoRedoToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leftRightSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        fileMenu.add(jMenuItem1);

        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        fileMenu.add(jMenuItem2);

        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        fileMenu.add(jMenuItem3);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(wursteditor.WurstEditorApp.class).getContext().getActionMap(WurstEditorView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        jMenuItem4.setText(resourceMap.getString("jMenuItem4.text")); // NOI18N
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText(resourceMap.getString("jMenuItem5.text")); // NOI18N
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText(resourceMap.getString("jMenuItem6.text")); // NOI18N
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText(resourceMap.getString("jMenuItem7.text")); // NOI18N
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText(resourceMap.getString("jMenuItem8.text")); // NOI18N
        jMenuItem8.setName("jMenuItem8"); // NOI18N
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText(resourceMap.getString("jMenuItem9.text")); // NOI18N
        jMenuItem9.setName("jMenuItem9"); // NOI18N
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText(resourceMap.getString("jMenuItem10.text")); // NOI18N
        jMenuItem10.setName("jMenuItem10"); // NOI18N
        jMenu1.add(jMenuItem10);

        jMenuItem11.setText(resourceMap.getString("jMenuItem11.text")); // NOI18N
        jMenuItem11.setName("jMenuItem11"); // NOI18N
        jMenu1.add(jMenuItem11);

        menuBar.add(jMenu1);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText(resourceMap.getString("jCheckBoxMenuItem1.text")); // NOI18N
        jCheckBoxMenuItem1.setName("jCheckBoxMenuItem1"); // NOI18N
        jMenu2.add(jCheckBoxMenuItem1);

        menuBar.add(jMenu2);

        jMenu3.setText(resourceMap.getString("jMenu3.text")); // NOI18N
        jMenu3.setName("jMenu3"); // NOI18N
        menuBar.add(jMenu3);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ErrorListScrollPane;
    private javax.swing.JTabbedPane RSTASplitPane;
    private javax.swing.JToolBar checkCompileToolbar;
    private javax.swing.JButton compileButton;
    private javax.swing.JList errorList;
    private javax.swing.JToolBar fileManagementToolbar;
    private javax.swing.JTree fileTree;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSplitPane leftRightSplitPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton newFileButton;
    private javax.swing.JButton newProjectButton;
    private javax.swing.JButton openProjectButton;
    private javax.swing.JScrollPane rSyntaxScrollPane;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton saveAllButton;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JTextArea syntaxCodeArea;
    private javax.swing.JSplitPane syntaxErrorSplitpane;
    private javax.swing.JTabbedPane tabbedFilePane;
    private javax.swing.JPanel treePanel;
    private javax.swing.JScrollPane treeScrollPane;
    private javax.swing.JButton undoButton;
    private javax.swing.JToolBar undoRedoToolbar;
    // End of variables declaration//GEN-END:variables
    

    private JDialog aboutBox;

    /**
     * @return the ErrorListScrollPane
     */
    public javax.swing.JScrollPane getErrorListScrollPane() {
        return ErrorListScrollPane;
    }

    /**
     * @return the checkCompileToolbar
     */
    public javax.swing.JToolBar getCheckCompileToolbar() {
        return checkCompileToolbar;
    }

    /**
     * @return the compileButton
     */
    public javax.swing.JButton getCompileButton() {
        return compileButton;
    }

    /**
     * @return the errorList
     */
    public javax.swing.JList getErrorList() {
        return errorList;
    }

    /**
     * @return the fileManagementToolbar
     */
    public javax.swing.JToolBar getFileManagementToolbar() {
        return fileManagementToolbar;
    }

    /**
     * @return the fileTree
     */
    public javax.swing.JTree getFileTree() {
        return fileTree;
    }

    /**
     * @return the jCheckBoxMenuItem1
     */
    public javax.swing.JCheckBoxMenuItem getjCheckBoxMenuItem1() {
        return jCheckBoxMenuItem1;
    }

    /**
     * @return the jMenu1
     */
    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    /**
     * @return the jMenu2
     */
    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    /**
     * @return the jMenu3
     */
    public javax.swing.JMenu getjMenu3() {
        return jMenu3;
    }

    /**
     * @return the jMenuItem1
     */
    public javax.swing.JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    /**
     * @return the jMenuItem10
     */
    public javax.swing.JMenuItem getjMenuItem10() {
        return jMenuItem10;
    }

    /**
     * @return the jMenuItem11
     */
    public javax.swing.JMenuItem getjMenuItem11() {
        return jMenuItem11;
    }

    /**
     * @return the jMenuItem2
     */
    public javax.swing.JMenuItem getjMenuItem2() {
        return jMenuItem2;
    }

    /**
     * @return the jMenuItem3
     */
    public javax.swing.JMenuItem getjMenuItem3() {
        return jMenuItem3;
    }

    /**
     * @return the jMenuItem4
     */
    public javax.swing.JMenuItem getjMenuItem4() {
        return jMenuItem4;
    }

    /**
     * @return the jMenuItem5
     */
    public javax.swing.JMenuItem getjMenuItem5() {
        return jMenuItem5;
    }

    /**
     * @return the jMenuItem6
     */
    public javax.swing.JMenuItem getjMenuItem6() {
        return jMenuItem6;
    }

    /**
     * @return the jMenuItem7
     */
    public javax.swing.JMenuItem getjMenuItem7() {
        return jMenuItem7;
    }

    /**
     * @return the jMenuItem8
     */
    public javax.swing.JMenuItem getjMenuItem8() {
        return jMenuItem8;
    }

    /**
     * @return the jMenuItem9
     */
    public javax.swing.JMenuItem getjMenuItem9() {
        return jMenuItem9;
    }

    /**
     * @return the leftRightSplitPane
     */
    public javax.swing.JSplitPane getLeftRightSplitPane() {
        return leftRightSplitPane;
    }

    /**
     * @return the mainPanel
     */
    public javax.swing.JPanel getMainPanel() {
        return mainPanel;
    }

    /**
     * @return the menuBar
     */
    public javax.swing.JMenuBar getMenuBar() {
        return menuBar;
    }

    /**
     * @return the newFileButton
     */
    public javax.swing.JButton getNewFileButton() {
        return newFileButton;
    }

    /**
     * @return the newProjectButton
     */
    public javax.swing.JButton getNewProjectButton() {
        return newProjectButton;
    }

    /**
     * @return the openProjectButton
     */
    public javax.swing.JButton getOpenProjectButton() {
        return openProjectButton;
    }

    /**
     * @return the rSTASplitPane
     */
    public javax.swing.JTabbedPane getRSTASplitPane() {
        return RSTASplitPane;
    }

    /**
     * @return the rSyntaxScrollPane
     */
    public javax.swing.JScrollPane getrSyntaxScrollPane() {
        return rSyntaxScrollPane;
    }

    /**
     * @return the redoButton
     */
    public javax.swing.JButton getRedoButton() {
        return redoButton;
    }

    /**
     * @return the saveAllButton
     */
    public javax.swing.JButton getSaveAllButton() {
        return saveAllButton;
    }

    /**
     * @return the saveFileButton
     */
    public javax.swing.JButton getSaveFileButton() {
        return saveFileButton;
    }

    /**
     * @return the syntaxCodeArea
     */
    public RSyntaxTextArea getSyntaxCodeArea() {
        return (RSyntaxTextArea) syntaxCodeArea;
    }

    /**
     * @return the syntaxErrorSplitpane
     */
    public javax.swing.JSplitPane getSyntaxErrorSplitpane() {
        return syntaxErrorSplitpane;
    }

    /**
     * @return the tabbedFilePane
     */
    public javax.swing.JTabbedPane getTabbedFilePane() {
        return tabbedFilePane;
    }

    /**
     * @return the treePanel
     */
    public javax.swing.JPanel getTreePanel() {
        return treePanel;
    }

    /**
     * @return the treeScrollPane
     */
    public javax.swing.JScrollPane getTreeScrollPane() {
        return treeScrollPane;
    }

    /**
     * @return the undoButton
     */
    public javax.swing.JButton getUndoButton() {
        return undoButton;
    }

    /**
     * @return the undoRedoToolbar
     */
    public javax.swing.JToolBar getUndoRedoToolbar() {
        return undoRedoToolbar;
    }

    /**
     * @return the aboutBox
     */
    public JDialog getAboutBox() {
        return aboutBox;
    }


	
}
