<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pscript"
    nsURI="http://www.peeeq.de/pscript/Pscript" nsPrefix="pscript">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//PackageDeclaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Import"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//NameDef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameDef" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="StmtReturn" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StmtIf" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenBlock" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statements"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlock" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statements"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StmtWhile" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statements"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StmtExpr" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expr"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExprList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NativeType" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//NameDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDef" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//NameDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//NameDef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDef" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//NameDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//TypeExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuncDef" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//NameDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//NameDef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//TypeExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Statements"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDef" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//NameDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//TypeExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprAssignment" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprOr" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprAnd" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprEquality" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprComparison" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprAdditive" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprMult" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprSign" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprNot" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprCustomOperator" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprMember" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprFunctioncall" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//ExprList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprIdentifier" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprIntVal" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprNumVal" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprStrval" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprBuildinFunction" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//ExprList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprBuildinOperator" eSuperTypes="platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.peeeq.Pscript/src-gen/de/peeeq/pscript/Pscript.ecore#//Expr"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
