//generated by parseq
package de.peeeq.wurstscript.ast;

class StmtIfImpl implements StmtIf, AstElementIntern {
	StmtIfImpl(WPos source, Expr cond, WStatements thenBlock, WStatements elseBlock) {
		if (source == null) throw new IllegalArgumentException();
		((AstElementIntern)source).setParent(this);
		this.source = source;
		if (cond == null) throw new IllegalArgumentException();
		((AstElementIntern)cond).setParent(this);
		this.cond = cond;
		if (thenBlock == null) throw new IllegalArgumentException();
		((AstElementIntern)thenBlock).setParent(this);
		this.thenBlock = thenBlock;
		if (elseBlock == null) throw new IllegalArgumentException();
		((AstElementIntern)elseBlock).setParent(this);
		this.elseBlock = elseBlock;
	}

	private AstElement parent;
	public AstElement getParent() { return parent; }
	public void setParent(AstElement parent) {
		if (parent != null && this.parent != null) { 			throw new Error("Parent of " + this + " already set: " + this.parent + "\ntried to change to " + parent); 		}
		this.parent = parent;
	}

	private WPos source;
	public void setSource(WPos source) {
		if (source == null) throw new IllegalArgumentException();
		((AstElementIntern)this.source).setParent(null);
		((AstElementIntern)source).setParent(this);
		this.source = source;
	} 
	public WPos getSource() { return source; }

	private Expr cond;
	public void setCond(Expr cond) {
		if (cond == null) throw new IllegalArgumentException();
		((AstElementIntern)this.cond).setParent(null);
		((AstElementIntern)cond).setParent(this);
		this.cond = cond;
	} 
	public Expr getCond() { return cond; }

	private WStatements thenBlock;
	public void setThenBlock(WStatements thenBlock) {
		if (thenBlock == null) throw new IllegalArgumentException();
		((AstElementIntern)this.thenBlock).setParent(null);
		((AstElementIntern)thenBlock).setParent(this);
		this.thenBlock = thenBlock;
	} 
	public WStatements getThenBlock() { return thenBlock; }

	private WStatements elseBlock;
	public void setElseBlock(WStatements elseBlock) {
		if (elseBlock == null) throw new IllegalArgumentException();
		((AstElementIntern)this.elseBlock).setParent(null);
		((AstElementIntern)elseBlock).setParent(this);
		this.elseBlock = elseBlock;
	} 
	public WStatements getElseBlock() { return elseBlock; }

	public AstElement get(int i) {
		switch (i) {
			case 0: return source;
			case 1: return cond;
			case 2: return thenBlock;
			case 3: return elseBlock;
			default: throw new IllegalArgumentException("Index out of range: " + i);
		}
	}
	public int size() {
		return 4;
	}
	public StmtIf copy() {
		return new StmtIfImpl(source.copy(), cond.copy(), thenBlock.copy(), elseBlock.copy());
	}
	@Override public void accept(CompilationUnit.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(StmtLoop.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(FunctionDefinition.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(TypeDef.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(FuncDef.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(ClassSlots.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(AstElementWithModifier.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(ConstructorDef.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(PackageOrGlobal.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(WStatement.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(OnDestroyDef.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(InitBlock.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(WPackage.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(StmtIf.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(ClassOrModule.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(WEntity.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(ClassSlot.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(ClassMember.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(TopLevelDeclaration.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(NameDef.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(JassToplevelDeclaration.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(WScope.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(StmtWhile.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(WStatements.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(WEntities.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(ModuleDef.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public void accept(ClassDef.Visitor v) {
		source.accept(v);
		cond.accept(v);
		thenBlock.accept(v);
		elseBlock.accept(v);
		v.visit(this);
	}
	@Override public <T> T match(WStatement.Matcher<T> matcher) {
		return matcher.case_StmtIf(this);
	}
	@Override public void match(WStatement.MatcherVoid matcher) {
		matcher.case_StmtIf(this);
	}

	@Override public String toString() {
		return "StmtIf(" + source + ", " +cond + ", " +thenBlock + ", " +elseBlock+")";
	}
	private boolean attr_attrNearestPackage_isCached = false;
	private PackageOrGlobal attr_attrNearestPackage_cache;
	public PackageOrGlobal attrNearestPackage() {
		if (!attr_attrNearestPackage_isCached) {
			attr_attrNearestPackage_cache = de.peeeq.wurstscript.attributes.AttrNearestPackage.calculate(this);
			attr_attrNearestPackage_isCached = true;
		}
		return attr_attrNearestPackage_cache;
	}
	private boolean attr_attrNearestFuncDef_isCached = false;
	private FuncDef attr_attrNearestFuncDef_cache;
	public FuncDef attrNearestFuncDef() {
		if (!attr_attrNearestFuncDef_isCached) {
			attr_attrNearestFuncDef_cache = de.peeeq.wurstscript.attributes.AttrNearestFuncDef.calculate(this);
			attr_attrNearestFuncDef_isCached = true;
		}
		return attr_attrNearestFuncDef_cache;
	}
	private boolean attr_attrNearestClassDef_isCached = false;
	private ClassDef attr_attrNearestClassDef_cache;
	public ClassDef attrNearestClassDef() {
		if (!attr_attrNearestClassDef_isCached) {
			attr_attrNearestClassDef_cache = de.peeeq.wurstscript.attributes.AttrNearestClassDef.calculate(this);
			attr_attrNearestClassDef_isCached = true;
		}
		return attr_attrNearestClassDef_cache;
	}
	private boolean attr_attrNearestClassOrModule_isCached = false;
	private ClassOrModule attr_attrNearestClassOrModule_cache;
	public ClassOrModule attrNearestClassOrModule() {
		if (!attr_attrNearestClassOrModule_isCached) {
			attr_attrNearestClassOrModule_cache = de.peeeq.wurstscript.attributes.AttrNearestClassDef.nearestClassOrModule(this);
			attr_attrNearestClassOrModule_isCached = true;
		}
		return attr_attrNearestClassOrModule_cache;
	}
}
