/*
 * generated by Xtext
 */
package de.peeeq.pscript.ui.outline;

import java.util.List;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

import de.peeeq.pscript.pscript.*;

/**
 * customization of the default outline structure
 * 
 */
public class PscriptTransformer extends	AbstractDeclarativeSemanticModelTransformer {
	/*
	public List<EObject> getChildren(FuncDef f) {
		return NO_CHILDREN;
	}
	
	public List<EObject> getChildren(PackageDeclaration p) {
		return p.eContents(); // .getElements();
	}
	*/
	
	public List<? extends EObject> getChildren(PackageDeclaration p) {
		EList<EObject> contents = p.eContents();
		return EcoreUtil2.typeSelect(contents, FuncDef.class);
	}
}
