/*
 * generated by Xtext
 */
package de.peeeq.pscript.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PscriptUiModule extends de.peeeq.pscript.ui.AbstractPscriptUiModule {
	public PscriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
