
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 08 23:56:37 CEST 2011
//----------------------------------------------------

package de.peeeq.wurstscript.parser;

/** CUP generated class containing symbol constants. */
public class TokenType {
  /* terminals */
  public static final int IDENTIFIER = 3;
  public static final int ENDGLOBALS = 63;
  public static final int GT = 12;
  public static final int TYPE = 61;
  public static final int IMPLEMENTS = 48;
  public static final int NOTEQ = 11;
  public static final int DIV_INT = 23;
  public static final int NOTHING = 67;
  public static final int ENDFUNCTION = 65;
  public static final int RBRACK = 32;
  public static final int INIT = 45;
  public static final int COMMA = 33;
  public static final int PUBLICREAD = 41;
  public static final int GLOBALS = 62;
  public static final int LBRACK = 31;
  public static final int LT = 13;
  public static final int DIV_REAL = 22;
  public static final int LOOP = 69;
  public static final int DESTROY = 77;
  public static final int INTEGER_LITERAL = 2;
  public static final int FALSE = 7;
  public static final int NOT = 17;
  public static final int ELSEIF = 75;
  public static final int ARRAY = 49;
  public static final int THEN = 74;
  public static final int ENDLOOP = 70;
  public static final int PACKAGE = 36;
  public static final int VAL = 39;
  public static final int EQ = 14;
  public static final int NATIVETYPE = 44;
  public static final int CLASS = 54;
  public static final int EXITWHEN = 71;
  public static final int TRUE = 6;
  public static final int NATIVE = 46;
  public static final int PLUS = 18;
  public static final int LPAR = 27;
  public static final int WHILE = 52;
  public static final int EXTENDS = 57;
  public static final int REAL_LITERAL = 5;
  public static final int INTERFACE = 47;
  public static final int RSQUARE = 30;
  public static final int MOD_REAL = 24;
  public static final int PUBLIC = 40;
  public static final int RETURN = 53;
  public static final int MULT = 21;
  public static final int ELSE = 51;
  public static final int CONSTRUCT = 59;
  public static final int GTEQ = 9;
  public static final int DOT = 26;
  public static final int STRING_LITERAL = 4;
  public static final int EQEQ = 8;
  public static final int NULL = 56;
  public static final int EOF = 0;
  public static final int LSQUARE = 29;
  public static final int THIS = 58;
  public static final int RPAR = 28;
  public static final int FUNCTION = 38;
  public static final int ENDIF = 76;
  public static final int LOCAL = 68;
  public static final int IMPORT = 43;
  public static final int MINUS = 19;
  public static final int CONSTANT = 64;
  public static final int LTEQ = 10;
  public static final int OR = 16;
  public static final int SET = 72;
  public static final int error = 1;
  public static final int IF = 50;
  public static final int ONDESTROY = 60;
  public static final int TAKES = 66;
  public static final int NEW = 55;
  public static final int RETURNS = 37;
  public static final int MOD_INT = 25;
  public static final int NL = 34;
  public static final int AND = 15;
  public static final int PRIVATE = 42;
  public static final int STATIC = 35;
  public static final int UMINUS = 20;
  public static final int CALL = 73;
}

