
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 28 23:47:16 CET 2011
//----------------------------------------------------

package de.peeeq.wurstscript.parser;

/** CUP generated class containing symbol constants. */
public class TokenType {
  /* terminals */
  public static final int ENDGLOBALS = 75;
  public static final int IDENTIFIER = 3;
  public static final int GT = 12;
  public static final int ARROW = 42;
  public static final int TYPE = 73;
  public static final int IMPLEMENTS = 60;
  public static final int NOTEQ = 11;
  public static final int DIV_INT = 23;
  public static final int NOTHING = 79;
  public static final int ENDFUNCTION = 77;
  public static final int RBRACK = 32;
  public static final int INIT = 57;
  public static final int COMMA = 33;
  public static final int PUBLICREAD = 52;
  public static final int GLOBALS = 74;
  public static final int LBRACK = 31;
  public static final int LT = 13;
  public static final int THISTYPE = 41;
  public static final int LOOP = 81;
  public static final int DIV_REAL = 22;
  public static final int PROTECTED = 54;
  public static final int DESTROY = 89;
  public static final int INTEGER_LITERAL = 2;
  public static final int FALSE = 7;
  public static final int NOT = 17;
  public static final int ELSEIF = 87;
  public static final int ARRAY = 61;
  public static final int OVERRIDE = 45;
  public static final int THEN = 86;
  public static final int ENDLOOP = 82;
  public static final int PACKAGE = 47;
  public static final int VAL = 50;
  public static final int EQ = 14;
  public static final int NATIVETYPE = 56;
  public static final int CLASS = 66;
  public static final int ABSTRACT = 38;
  public static final int EXITWHEN = 83;
  public static final int TRUE = 6;
  public static final int NATIVE = 58;
  public static final int PLUS = 18;
  public static final int LPAR = 27;
  public static final int WHILE = 64;
  public static final int USE = 37;
  public static final int EXTENDS = 69;
  public static final int MODULE = 36;
  public static final int REAL_LITERAL = 5;
  public static final int INTERFACE = 59;
  public static final int RSQUARE = 30;
  public static final int MOD_REAL = 24;
  public static final int FOR = 40;
  public static final int PUBLIC = 51;
  public static final int RETURN = 65;
  public static final int MULT = 21;
  public static final int ELSE = 63;
  public static final int CONSTRUCT = 71;
  public static final int GTEQ = 9;
  public static final int DOT = 26;
  public static final int STRING_LITERAL = 4;
  public static final int EQEQ = 8;
  public static final int NULL = 68;
  public static final int EOF = 0;
  public static final int SEMICOLON = 34;
  public static final int LSQUARE = 29;
  public static final int THIS = 70;
  public static final int RPAR = 28;
  public static final int FUNCTION = 49;
  public static final int ENDIF = 88;
  public static final int LOCAL = 80;
  public static final int IMPORT = 55;
  public static final int IT = 43;
  public static final int MINUS = 19;
  public static final int CONSTANT = 76;
  public static final int IMMUTABLE = 44;
  public static final int LTEQ = 10;
  public static final int IN = 39;
  public static final int OR = 16;
  public static final int SET = 84;
  public static final int error = 1;
  public static final int CASTTO = 90;
  public static final int IF = 62;
  public static final int ONDESTROY = 72;
  public static final int TAKES = 78;
  public static final int NEW = 67;
  public static final int RETURNS = 48;
  public static final int MOD_INT = 25;
  public static final int NL = 35;
  public static final int AND = 15;
  public static final int PRIVATE = 53;
  public static final int STATIC = 46;
  public static final int UMINUS = 20;
  public static final int CALL = 85;
}

